spring.couchbase.connection-string=127.0.0.1
spring.couchbase.user-name=Administrator
spring.couchbase.password=senha_secreta

spring.data.couchbase.bucket-name=fitness_app

spring.data.couchbase.auto-index=true
