# Conexão com o Cluster Couchbase local
spring.couchbase.connection-string=127.0.0.1
spring.couchbase.user-name=Administrator
spring.couchbase.password=senha_secreta

# Nome do Bucket que você criou na interface web
spring.data.couchbase.bucket-name=fitness_app

# Isso permite que o Spring crie os índices primários automaticamente caso não existam
spring.data.couchbase.auto-index=true